### ISSUE TITLE
file content replaced by "Environment variable TERM not defined!" when formating

### ISSUE THREAD

**Issue by ayoub-benali** [fedragon/scafor#2]
I have ubuntu 18.04 and after installing the plugin and nailgun the file content is being replaced by the string "Environment variable TERM not defined!".  Seems like the `subprocess.Popen(` need to do something extra for nailgun

**Comment by fedragon** [comment]
Hi @ayoub-benali although it honestly feels like an issue on your side (`TERM` is a basic env var), I have just submitted version 3.0.1 with changes that set a value for the variable if it's not there, can you please update and let me know if it solves your issue?

**Comment by fedragon** [comment]
No reaction in almost 1.5 years, closing the issue
