### ISSUE TITLE
Issues with nailgun 1.0.0

### ISSUE THREAD

**Issue by LukaszByczynski** [fedragon/scafor#4]
After I created `scalafmt_ng` with following command:

```
./coursier bootstrap --standalone org.scalameta:scalafmt-cli_2.12:2.0.0 \
  -o /usr/local/bin/scalafmt_ng -f --main com.martiansoftware.nailgun.NGServer

```

I have issues with the plugin:

```
Starting Nailgun ...
About to format /Users/lukasz/IdeaProjects/bizbeam-nt/app/controllers/TestController.scala
java.io.IOException: Unknown stream type: H
	at com.martiansoftware.nailgun.NGInputStream.readHeader(NGInputStream.java:73)
```

My nailgun version is 1.0.0.

**Comment by LukaszByczynski** [comment]
Ok. I close this issue due a fact Metals and LSP client support scalafmt out of the box.

**Comment by fedragon** [comment]
@LukaszByczynski sorry for the late reaction, I was on holiday. I built this plugin before Metals came out but, as you indeed pointed out, now it is hardly convenient to use
